/**
 * Generate a point.
 *
 * @param {function(object): number} params.y - The y-coordinate accessor.
 * @returns {Object} point - The point generated by the factory.
 */
function generatePoint(params) {
  // Function implementation
}
